// Fuel Savings
export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

// Customers
export const SEARCH_CUSTOMERS = 'SEARCH_CUSTOMERS';
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS';

// Loadings
export const LOADING = 'LOADING';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';

// Login
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
